version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - /dev/gpiomem
    volumes:
      - /dev:/dev
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    privileged: true
    devices:
      - /dev/gpiomem
    volumes:
      - /dev:/dev
    profiles: ["test"]