FROM python:3.11-slim

WORKDIR /test
ENV PYTHONPATH=/test

RUN apt-get update && apt-get install -y python3-rpi.gpio && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app/ ./app
COPY tests/ ./tests

CMD ["pytest", "tests"]